export const FormParam: {} = {
  cpfCnpj: {
    label: "CPF/CNPJ",
    errorMsg: "",
    required: true,
    inputType: "input",
    inputMode: "numeric",
    placeholder: "CPF ou CNPJ",
    masks: ["###.###.###-##", "##.###.###/####-##"],
    value: "",
    valueMasked: "",
    maxLength: 18,
    function: ["validateCPF"],
  },
  cep: {
    label: "CEP",
    errorMsg: "",
    required: true,
    inputType: "input",
    inputMode: "numeric",
    placeholder: "00000-000",
    masks: ["#####-###"],
    value: "",
    valueMasked: "",
    maxLength: 9,
    link: {
      paramBeginning: "https://viacep.com.br/ws/",
      paramSize: 8,
      paramEnd: "/json/",
    },
  },
  logradouro: {
    label: "Logradouro",
    errorMsg: "",
    required: true,
    inputType: "input",
    placeholder: "Rua/Av...",
    value: "",
    maxLength: 100,
  },
  numero: {
    label: "Número",
    errorMsg: "",
    required: true,
    inputType: "input",
    placeholder: "0000",
    value: "",
    maxLength: 4,
  },
  complemento: {
    label: "Complemento",
    errorMsg: "",
    inputType: "input",
    placeholder: "Apto./Bloco...",
    value: "",
    maxLength: 100,
  },
  bairro: {
    label: "Bairro",
    errorMsg: "",
    required: true,
    inputType: "input",
    placeholder: "Bairro...",
    value: "",
    maxLength: 100,
  },
  localidade: {
    label: "Cidade",
    errorMsg: "",
    required: true,
    inputType: "input",
    placeholder: "Cidade...",
    value: "",
    maxLength: 100,
  },
  uf: {
    label: "UF",
    errorMsg: "",
    required: true,
    inputType: "input",
    placeholder: "UF...",
    value: "",
    maxLength: 2,
  },
};
