export const FormParam: {} = {
  cep: {
    label: "CEP",
    inputType: "input",
    inputMode: "numeric",
    placeholder: "00000-000",
    masks: ["#####-###"],
    value: "",
    valueMasked: "",
    maxLength: 9,
    link: {
      paramBeginning: "https://viacep.com.br/ws/",
      paramEnd: "/json/",
      correspondKey: ["logradouro"],
    },
  },
  logradouro: {
    label: "Logradouro",
    inputType: "input",
    placeholder: "Rua/Av...",
    value: "",
    maxLength: 100,
  },
  numero: {
    label: "Número",
    inputType: "input",
    placeholder: "0000",
    value: "",
    maxLength: 4,
  },
  complemento: {
    label: "Complemento",
    inputType: "input",
    placeholder: "Apto./Bloco...",
    value: "",
    maxLength: 100,
  },
  bairro: {
    label: "Bairro",
    inputType: "input",
    placeholder: "Bairro...",
    value: "",
    maxLength: 100,
  },
  localidade: {
    label: "Cidade",
    inputType: "input",
    placeholder: "Cidade...",
    value: "",
    maxLength: 100,
  },
  uf: {
    label: "UF",
    inputType: "input",
    placeholder: "UF...",
    value: "",
    maxLength: 2,
  },
};
